FROM archlinux:latest

ARG USER=ci

RUN pacman -Syu --noconfirm \
    ca-certificates curl git \
    clang make unzip \               # Equivalent to build-essential, clang, etc.
    ninja sudo python3 cmake \
    && rm -rf /var/cache/pacman/pkg/


RUN pip install conan --break-system-packages

RUN useradd -m ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/${USER}/workspace
