FROM archlinux:latest

ARG USER=ci

RUN pacman -Syu --noconfirm \
    ca-certificates curl git \
    gcc make unzip clang-format \
    ninja sudo python3 python-pip cmake \
    && rm -rf /var/cache/pacman/pkg/


RUN pip install conan --break-system-packages

RUN useradd -m ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/${USER}/workspace
