name: HyperCPU CI/CD Pipeline (build HyperCPU on different platforms)

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: hyperwin/hcpu-ci:${{ matrix.config.tag }}
    name: "Build on ${{matrix.config.name}}"
    strategy:
      matrix:
        config:
          - tag: fedora
            name: Fedora
          - tag: debian-stable
            name: Debian Stable
          - tag: debian-unstable
            name: Debian Unstable
          - tag: archlinux
            name: Arch Linux
          - tag: gentoo-glibc
            name: Gentoo GLibc
          - tag: gentoo-musl
            name: Gentoo Musl
          - tag: alpine
            name: Alpine
          - tag: ubuntu
            name: Ubuntu
    
    steps:
      - run: |
          set -e
          DISTRO=$( cat /etc/*-release | tr [:upper:] [:lower:] | grep -Poi '(debian|ubuntu|fedora|gentoo|alpine)' | uniq )
          if [ "$DISTRO" == "gentoo" ]; then source /etc/profile; fi
          git clone https://github.com/HyperWinX/HyperCPU.git --recursive  && cd HyperCPU
          git switch "${{ github.head_ref }}"
          cd dist/pog && git pull origin master && cd ../..
          cmake -S. -Bbuild -DHCPU_COMPILER=clang -DHCPU_LTO=ON -DHCPU_SANITIZERS=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target run-all-tests-github -j8
          cmake --build build --target default -j8
          rm -rf build
          cmake -S. -Bbuild -DHCPU_COMPILER=gcc -DHCPU_LTO=ON -DHCPU_SANITIZERS=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target run-all-tests-github -j8
          cmake --build build --target default -j8
