name: HyperCPU CI/CD Pipeline (build HyperCPU on different platforms)

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hyperwin/hcpu-ci:${{ matrix.config.tag }}
      options: --user root
    name: "Build on ${{matrix.config.name}}"
    strategy:
      matrix:
        config:
          - tag: fedora
            name: Fedora
          - tag: debian-stable
            name: Debian Stable
          - tag: debian-unstable
            name: Debian Unstable
          - tag: archlinux
            name: Arch Linux
          - tag: gentoo-glibc
            name: Gentoo GLibc
          - tag: gentoo-musl
            name: Gentoo Musl
          - tag: alpine
            name: Alpine
          - tag: ubuntu
            name: Ubuntu

    steps:
      - run: |
          set -e
          DISTRO=$( cat /etc/*-release | tr [:upper:] [:lower:] | grep -Poi '(debian|ubuntu|fedora|gentoo|alpine)' | uniq )
          if [ "$DISTRO" == "gentoo" ]; then
            source /etc/profile
          fi
          git clone https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git && cd HyperCPU
          git checkout ${{ github.event.pull_request.head.sha }}
          git submodule update --init --recursive

          conan profile detect && conan install . --build=missing
          bazelisk build //src/... //tests/... --config=linux-opt
