name: HyperCPU CI/CD Pipeline (format)

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hypercpu-project/hypercpu-builder:latest
      options: --init
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R ci:ci "$GITHUB_WORKSPACE"

      - name: Run formatters
        run: sudo -u ci bazelisk run :format

      - name: Check diff
        run: sudo -u ci git diff --quiet
