name: HyperCPU CI/CD Pipeline (compile project)

on:
  workflow_call:

jobs:
  testing:
    name: Compile (${{ matrix.compiler }} on ${{ matrix.distribution }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hypercpu-project/hypercpu-builder-${{ matrix.compiler }}-${{ matrix.distribution }}:latest
      options: --init
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        distribution: [debian, ubuntu, fedora, arch]
        build-type: [Release, Debug]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies with Conan
        run: sudo -u ci conan profile detect
          
      - name: Fix permissions
        run: chown -R ci:ci "$GITHUB_WORKSPACE"

      - name: Build project (Release, with ${{ matrix.compiler }} compiler)
        run: |
          sudo -u ci conan install . --build=missing -s build_type=${{ matrix.build_type }}
          if [[ "${{ matrix.build_type }}" = "Release" ]]; then
            sudo -u ci cmake --preset conan-release -DINSTALL_TESTS=1
          else
            sudo -u ci cmake --preset conan-debug -DINSTALL_TESTS=1
          fi
          sudo -u ci cmake --build build/Release -j$(nproc)
          sudo -u ci cmake --build build/Release --target package

      - name: Run all tests
        run: |
          sudo -u ci build/Release/tests/Integration/integration-tests
          sudo -u ci build/Release/tests/Modular/modular-tests