name: HyperCPU CI/CD Pipeline (compile project)

on:
  workflow_call:

jobs:
  testing:
    name: Compile (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hypercpu-project/hypercpu-builder:latest
      options: --init
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Fix permissions
        run: chown -R ci:ci "$GITHUB_WORKSPACE"

      - name: Install dependencies with Conan
        run: |
          sudo -u ci
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            export CC=clang
            export CXX=clang++
          else
            export CC=gcc
            export CXX=g++
          fi
          conan profile detect

      - name: Build project (Release, with ${{ matrix.compiler }} compiler)
        run: |
          sudo -u ci cmake --preset conan-release
          sudo -u ci cmake --build build/Release -j$(nproc)

      - name: Upload package tarball
        uses: actions/upload-artifact@v4
        with:
          name: hcpu-tarballs-${{ matrix.compiler }}
          path: |
            bazel-bin/tools/packaging/*.tar.gz
            !bazel-bin/tools/packaging/hcpu.tar.gz
          if-no-files-found: error
