name: HyperCPU CI/CD Pipeline (compile project)

on:
  workflow_call:

jobs:
  testing:
    name: Compile (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hypercpu-project/hypercpu-builder:latest
      options: --init
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies with Conan
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            export CC=$(which clang)
            export CXX=$(which clang++)
          else
            export CC=$(which gcc)
            export CXX=$(which g++)
          fi
          sudo -u ci env CC=$CC CXX=$CXX conan profile detect
          
      - name: Fix permissions
        run: chown -R ci:ci "$GITHUB_WORKSPACE"

      - name: Build project (Release, with ${{ matrix.compiler }} compiler)
        run: |
          sudo -u ci conan install . --build=missing
          sudo -u ci cmake --preset conan-release
          sudo -u ci cmake --build build/Release -j$(nproc)
          sudo -u ci cmake --build build/Release --target package

      - name: Upload package tarball
        uses: actions/upload-artifact@v4
        with:
          name: hcpu-tarballs-${{ matrix.compiler }}
          path: |
            build/Release/*.tar.gz
          if-no-files-found: error
