name: HyperCPU CI/CD Pipeline (feature branch)

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    container: hyperwin/hcpu-ci:debian-unstable
    if: (github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev') || !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Build and test with GCC on Release profile
        run: |
          python3 scripts/build.py -icb             \
            --config Release                        \
            --build-dir build                       \
            -D CMAKE_CXX_COMPILER:STRING=g++        \
            -D CMAKE_C_COMPILER:STRING=gcc          \
            --profiles-detection
          cd build/Release && ctest -V && cd ../..
          python3 scripts/build.py -r --config Release --build-dir build
      
      - name: Build and test with LLVM on Release profile
        run: |
          python3 scripts/build.py -icb             \
            --config Release                        \
            --build-dir build                       \
            -D CMAKE_CXX_COMPILER:STRING=clang++-19 \
            -D CMAKE_C_COMPILER:STRING=clang-19     \
            --profiles-detection
          cd build/Release && ctest -V && cd ../..
          python3 scripts/build.py -r --config Release --build-dir build

      - name: Cleanup (Conan cache + leftovers in build)
        run: |
          rm -r build/
