name: HyperCPU CI/CD Pipeline (version incrementing)

on:
  push:
    branches:
      - master

jobs:
  versioning-increment:
    runs-on: ubuntu-latest
    container:
      image: hyperwin/hcpu-ci:debian-unstable

    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - increment: patch
            marker: '[ci-patch-increase]'
          - increment: minor
            marker: '[ci-minor-increase]'
          - increment: major
            marker: '[ci-major-increase]'

    if: >
      contains(github.event.head_commit.message, '[ci-patch-increase]') ||
      contains(github.event.head_commit.message, '[ci-minor-increase]') ||
      contains(github.event.head_commit.message, '[ci-major-increase]')

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: fregante/setup-git-user@v1

      - name: Fire increment version script (${{ matrix.increment }})
        id: increment
        run: |
          tools/increment_version.py --increment ${{ matrix.increment }} >> $GITHUB_OUTPUT

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Increment ${{ matrix.increment }} version to ${{ steps.increment.outputs }}"
